version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: kafka_zookeeper
    ports:
      - ${ZOOKEEPER_PORT:-2181}:2181
    environment:
      - TZ=${TIMEZONE:-Europe/London}
    volumes:
      - zoneinfo:/usr/share/zoneinfo/
    restart: ${ZOOKEEPER_RESTART:-no}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - ${KAFKA_PORT:-9092}:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:${ZOOKEEPER_PORT:-2181}
      - TZ=${TIMEZONE:-Europe/London}
    env_file:
      - ./.env.kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - zoneinfo:/usr/share/zoneinfo/
    restart: ${KAFKA_RESTART:-no}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka_ui
    ports:
      - ${KAFKA_UI_PORT:-8080}:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:${KAFKA_PORT:-9092}
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:${ZOOKEEPER_PORT:-2181}
      - KAFKA_CLUSTERS_0_READONLY=false
      - TZ=${TIMEZONE:-Europe/London}
    volumes:
      - zoneinfo:/usr/share/zoneinfo/
    restart: ${KAFKA_UI_RESTART:-no}
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  zoneinfo:
